# Generated by Django 5.0.7 on 2024-07-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='varified',
            field=models.BooleanField(default=True),
        ),
    ]
