# Generated by Django 5.0.7 on 2024-07-14 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_varified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='varified',
            new_name='verified',
        ),
    ]
