# Generated by Django 5.0.7 on 2024-07-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_book_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='new_arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='trending',
            field=models.BooleanField(default=False),
        ),
    ]
