# Generated by Django 5.0.7 on 2024-07-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
