# Generated by Django 5.0.7 on 2024-07-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_transaction_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='extra_days',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
